---
- name: UNATTENDED  | place 50unattended-upgrade
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: UNATTENDED  | place 20auto-upgrades
  template:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: UNATTENDED | restart
  service:
    name: unattended-upgrades
    state: restarted